"""add channel to transactions

Revision ID: 499ecdad32fc
Revises: 8ea6129d631f
Create Date: 2025-10-13 15:37:38.457090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499ecdad32fc'
down_revision: Union[str, None] = '8ea6129d631f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'paystack_email_token')
    op.add_column('transactions', sa.Column('channel', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'channel')
    op.add_column('subscriptions', sa.Column('paystack_email_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
