"""Add Paystack subscription fields

Revision ID: 8ea6129d631f
Revises: 7fadcd4ec6a7
Create Date: 2025-10-13 12:01:58.547281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ea6129d631f'
down_revision: Union[str, None] = '7fadcd4ec6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flash_card_sets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('plan_prices', 'interval_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('plan_prices', 'scope_type',
               existing_type=postgresql.ENUM('global', 'continent', 'country', name='regionscopetype'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('plan_prices', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('subscriptions', sa.Column('paystack_email_token', sa.String(), nullable=True))
    op.alter_column('subscriptions', 'billing_interval',
               existing_type=postgresql.ENUM('month', 'year', name='billinginterval'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('subscriptions', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.add_column('transactions', sa.Column('paystack_customer_code', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('paystack_authorization_code', sa.String(), nullable=True))
    op.alter_column('transactions', 'transaction_type',
               existing_type=postgresql.ENUM('initial', 'recurring', 'refund', name='transactiontype'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'transaction_type',
               existing_type=postgresql.ENUM('initial', 'recurring', 'refund', name='transactiontype'),
               server_default=sa.text("'initial'::transactiontype"),
               existing_nullable=False)
    op.drop_column('transactions', 'paystack_authorization_code')
    op.drop_column('transactions', 'paystack_customer_code')
    op.alter_column('subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('subscriptions', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('subscriptions', 'billing_interval',
               existing_type=postgresql.ENUM('month', 'year', name='billinginterval'),
               server_default=sa.text("'month'::billinginterval"),
               existing_nullable=True)
    op.drop_column('subscriptions', 'paystack_email_token')
    op.alter_column('plan_prices', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('plan_prices', 'scope_type',
               existing_type=postgresql.ENUM('global', 'continent', 'country', name='regionscopetype'),
               server_default=sa.text("'global'::regionscopetype"),
               existing_nullable=False)
    op.alter_column('plan_prices', 'interval_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('flash_card_sets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
